website/models.py
from . import db
from flask_login import UserMixin
from . import login
from sqlalchemy import Column, String, Integer, VARCHAR, BigInteger


class users(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.VARCHAR(45), unique=True)
    password = db.Column(db.VARCHAR(45))

class employees(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.VARCHAR(45))
    last_name = db.Column(db.VARCHAR(45))
    phone_number = db.Column(db.BigInteger)
    department = db.Column(db.VARCHAR(45))

@login.user_loader
def load_user(id):
    return users.query.get(int(id))

website/__init__.py
from ipaddress import ip_address
from flask import Flask, render_template, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'asdf'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mssql+pymssql://ale:Test12345!@sqlflasktest.database.windows.net/test'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)
    login.init_app(app)
    login.login_view = 'auth.login'
    

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")


    return app

    

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import users
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get("password")

        user = users.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                flash('Logged in successfully!')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password', category='error')
        else:
            flash('Email does not exist', category='error')
    return render_template("login.html", user=current_user)
    
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from flask_sqlalchemy import SQLAlchemy
from .models import employees
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)

@views.route('/search', methods=['GET', 'POST'])
@login_required

def search():

    print(request.method)
    result=[]
    default_page = 2
    page = request.args.get('page', 1, type=int)
    search_value = request.args.get('search_value')
    search_type = request.args.get('search_type')
    name_form = request.form.get('name_search')

    if page >= 1 and search_type == 'search_one' and request.method == 'GET':
        print ('1')
        name_form = search_value
        result=search_one(page, name_form)
        
    elif page >= 1 and search_type == 'search_all' and request.method == 'GET':
        result=search_all(page)
        print ('2')

    if request.method == 'POST' and request.form.get('Search') == 'Search':
        
        if search_type == 'search_all':
            default_page = 1
            print ('3')

        else:
            default_page = page
            print ('4')

        search_type='search_one'
        search_value=name_form
        result=search_one(default_page, name_form)

    

    if request.method == 'POST' and request.form.get('Search All') == 'Search All':

        if search_type == 'search_one':
            default_page = 1
            print ('5')

        else:
            default_page = page
            print ('6')

        search_type='search_all'
        result=search_all(default_page)


        flash('All employees listed')

    return render_template("search.html", user=current_user, result=result, search_value=search_value, search_type=search_type, default_page=default_page)


def search_one(page, name_form):

    result=[]
    if(len(name_form) > 2):
        result = employees.query.filter(employees.first_name.contains(name_form)).order_by(employees.id).paginate(page=page, per_page=2)

        if result:
                flash('Users found!')

        else:
                flash('Users not found', category='error')

    else:
        flash('Please provide more than 2 characters', category='error')

    return result
    

def search_all(page):

    result = employees.query.order_by(employees.last_name.asc()).paginate(page=page, per_page=20)
    
    return result


@views.route('/add_employee', methods=['GET', 'POST'])
@login_required

def add_employee():

    raw_data = employees.query.with_entities(employees.department).distinct()
    department_list = [item[0] for item in raw_data]

    if request.method == 'POST':
        name_add = request.form.get('add_name')
        lastname_add = request.form.get('add_lastname')
        phonenumber_add = request.form.get('add_phonenumber')
        department_add = request.form.get('add_department')

        if(len(name_add) <= 2):
            flash("First name has to be at lest 2 characters long")

        elif (len(lastname_add) <=2 ):
            flash("Last name has to be at lest 2 characters long")
        
        elif (len(phonenumber_add) <= 6):
            flash("Phone has to be at lest 6 characters long")
        
        elif department_add == None:
           flash("Please choose Department", category='error')

        else:
            new_employee = employees(first_name=name_add, last_name=lastname_add, phone_number=phonenumber_add, department=department_add)
            db.session.add(new_employee)
            db.session.commit()
            flash('Employee Added!', category='success')

    return render_template("add_employee.html", dept_list=department_list,  user=current_user)

@views.route('/delete-employee', methods=['POST'])
def delete_employee():

    employee = json.loads(request.data)
    employeeId = employee['employeeId']
    employee = employees.query.filter_by(id=employeeId)
    if employee:
        employee.delete()
        db.session.commit()
        flash('Employee Deleted')
        return jsonify({})
    else:
        flash('user does not exist', category='error')

website/templates/add_employee.html
{% extends "base.html" %}

{% block title %}Add Employee{% endblock %}

{%block content%}

<form method="POST">
  <h3 align="center">Add Employee</h3>
  <div class="form-group">
    <label for="add_name">First Name</label>
    <input
      type="text"
      class="form-control"
      id="add_name"
      name="add_name"
      placeholder="Enter First Name"
    />
  </div>


   <div class="form-group">
    <label for="add_lastname">Last Name</label>
    <input
      type="text"
      class="form-control"
      id="add_lastname"
      name="add_lastname"
      placeholder="Enter Last Name"
    /> 

  </div>

  <div class="form-group">
    <label for="add_phonenumber">Phone Number</label>
    <input
      type="text"
      class="form-control"
      id="add_phonenumber"
      name="add_phonenumber"
      placeholder="Enter Phone Number"
    />

  </div>

  <div >
    <label>Chooose Department</label>
    <br />
    <select 
    class="orm-select form-select-lg mb-3" 
    aria-label=".form-select-sm example" 
    id="add_department"
    name="add_department"
    >
      {% for each in dept_list %}
      <option value="{{each}}">{{each}}</option>
      {% endfor %}
    </select>
  </div>

  <br />

  <button type="submit" class="btn btn-primary">Add Employee</button>



</form>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="search" href="/">Home</a>
          <a class="nav-item nav-link" id="search" href="/search">Search</a>
          <a class="nav-item nav-link" id="add_employee" href="/add_employee">Add Employee</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">

      {% block content%}

      {% endblock %}

    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>

  </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{%block content%}
<h1> Home Page </h1>
{% endblock%}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{%block content%}

<form method="POST">
    <h3 align="center">Log In</h3>
    <div class="form-group">
      <label for="email">Email Adress</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter Email"
      />
    </div>
  
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter Password"
      />
  
    </div>
  
  
    <br />
  
    <button type="submit" class="btn btn-primary">Login</button>
  
  
  
  </form>


{% endblock %}

website/templates/search.html
{% extends "base.html" %} {% block title %}Search{% endblock %} {% block
  content %}

  <form method="POST">
      <h3 align="center">Search</h3>
      <div class="form-group">
        <label for="Name">Search by Name</label>
        <input
          type="search"
          class="form-control"
          id="name_search"
          name="name_search"
          placeholder="Search name"
        />
      </div>
      <center>
      <input type="submit" class="btn btn-primary" value="Search" name="Search"/>
      &nbsp&nbsp
      <input type="submit" class="btn btn-primary" value="Search All" name="Search All"/>
      </center>
      <br />
    </form>
      {% if result %}
        <table class="table">
          <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
          </tr>
        </thead>
      {% for employee in result.items: %}
        <tbody>
      <tr>
        <td>{{ employee.id }}</td>
        <td>{{ employee.first_name }} {{ employee.last_name }}</td>
        <td>{{ employee.phone_number }}</td>
        <td>{{ employee.department }}</td>
        <td><button type="button" class="btn btn-danger" onclick="deleteEmployee({{ employee.id }})">Delete Employee</button></td>
      </tr>
      </tbody>
      {% endfor %}
      </table>
      {% for page_num in result.iter_pages(left_edge=3, right_edge=3, left_current=3, right_current=4): %}

      {% if page_num %}
      {% if result.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('views.search', page=page_num, search_type=search_type, search_value=search_value) }}">{{ page_num }}</a>
      {% else: %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('views.search', page=page_num, search_type=search_type, search_value=search_value) }}">{{ page_num }}</a>
      {% endif %}
      {% else: %}
      ...
      {% endif %}
      {% endfor %}
      {% endif %}


  {% endblock%}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign UP{% endblock %} {% block
content %}

<form method="POST">
  <h3 align="center">Sign UP</h3>
  <div class="form-group">
    <label for="email">Email Adress</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter Email"
    />
  </div>


  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter First Name"
    />

  </div>

  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter Password"
    />

  </div>

  <div class="form-group">
    <label for="password2">Confirm Password</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm Password"
    />

  </div>

  <br />

  <button type="submit" class="btn btn-primary">Submit</button>



</form>

{% endblock%}